### DISCUSSION TITLE
Minimum and Maximum Temperatures

### DISCUSSION THREAD

**Discussion by TheSgrash** [Arnold-n/P1P2MQTT#124] [Q&A] [answered]
Hi Arnold and community,
I successfully integrated my old Daikin heatpump (model **FBQ50B8V1**).
I was playing around with Thermostat card using the `climate.hc_setpoints_setpoint_cooling` entity and I see there is something like an hardcoded range of 14-28 Celsius degrees while my model can work in the range 16-32.

I looked on Home Assistant forum and I found two hints [here](https://community.home-assistant.io/t/thermostat-card-min-and-max-temp-display/174186/4)

First one is to work on `[path_to_homeassistant]/lib/[python_version]/site-packages/homeassistant/components/climate/__init__.py` but here I found I have default values (7-35)

so I tried the second hint and added the `customize.yaml` file with

```yaml
climate.hc_setpoints_setpoint_cooling:
    max_temp: 32
    min_temp: 16
climate.hc_setpoints_setpoint_heating:
    max_temp: 32
    min_temp: 16
```
this last one changed the behaviour of the card showing my desired range but if I try to set e.g. 29 degrees a popup error message appears and I see same message into logs
```
ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [546373553600] Provided temperature 32.0 is not valid. Accepted range is 14.0 to 28.0
```

so my questions are: 
- is the range something you set on your side? 
- if yes, is it customizable or how can I change it?
- does anyone had same issue?
