### DISCUSSION TITLE
Homewizard kWh meter installation

### DISCUSSION THREAD

**Discussion by caveman85** [Arnold-n/P1P2MQTT#206] [Q&A]
Is there anyone who can provide some more (installation) details on how to get the HomeWizard-kWh-MQTT-bridge up and running on a ESP01 device? And how to connect it to P1P2 bridge

**Comment by Arnold-n** [comment]
If you are running Home Assistant, you do not need the ESP01 device. Instead, you can set up the HomeWizard integration in HA and add to the yaml configurations in HA:

```
- id: '999999999'
  alias: output kWh meter via MQTT
  triggers:
  - entity_id: sensor.kwh_meter_power
    trigger: state
  - trigger: time_pattern
    seconds: '0'
  actions:
  - data:
      topic: P1P2/P/meter/U/9/Electricity_Power
      payload: '{{ states(''sensor.kwh_meter_power'') }}'
    action: mqtt.publish
```
