### DISCUSSION TITLE
Automations in Home-Assistant

### DISCUSSION THREAD

**Discussion by sa3lej** [Arnold-n/P1P2MQTT#34] [Show and tell]
I have finished my first automations in Home-Assistant - my main goal is cut costs by trying to limit heating during very high cost periods (usually daytime). I use Tibber as a provider and they provide an attribute in their api called "Price level" that in turn is dynamic: "Price level based on trailing price average (3 days for hourly values and 30 days for daily values)" - i have mapped that to a simple 1-5 sensor where 1 is very cheap and 5 is very expensive. 

My automations build on that sensor and an average temp based on the room temperature from my (daikin) controller and a separate temp sensor in another room of the house. I'm pretty sure i will need to adjust these to dial stuff in and perhaps use calculations based on the actual price instead of their price level. But so far everything checks out and seems stable. :) 

Turn off pump when price is to high and temp is above 18 and notify me:

```
alias: Pump off when price is very high
description: ""
trigger:
  - platform: template
    value_template: "{{ states('sensor.elpris') | int(0) > 3 }}"
    alias: Very expensive electricity
condition:
  - condition: template
    value_template: "{{ states('sensor.medeltemp') | int(0) > 18 }}"
action:
  - service: mqtt.publish
    data:
      topic: P1P2/W
      payload: Z0
  - device_id: 7e429c0ad21a3d746bee3b0dae58cada
    domain: mobile_app
    type: notify
    message: Värmen är nu avstängd!
    title: Elen är dyr
mode: single
```

Turn on pump when price is low and temp is above 20:
```
alias: Pump on when temp is low and price is cheap
description: ""
trigger:
  - platform: template
    value_template: "{{ states('sensor.elpris') | int(0) < 3 }}"
    alias: Cheap electricity
condition:
  - condition: template
    value_template: "{{ states('sensor.medeltemp') | int(0) < 20 }}"
    alias: Temp is lower than 20
action:
  - service: mqtt.publish
    data:
      topic: P1P2/W
      payload: Z1
mode: single
```

And finally to account for the times when the price is "Normal":
```
alias: Pump on when normal price
description: ""
trigger:
  - platform: template
    value_template: "{{ states('sensor.elpris') | int(0) == 3 }}"
    alias: Normal price
condition:
  - condition: template
    value_template: "{{ states('sensor.medeltemp') | int(0) < 19 }}"
action:
  - service: mqtt.publish
    data:
      topic: P1P2/W
      payload: Z1
mode: single
```
