### DISCUSSION TITLE
Home assistant : Climate object for room and LWT temperature

### DISCUSSION THREAD

**Discussion by trantoriana** [Arnold-n/P1P2MQTT#59] [Show and tell]
Hi,

I have been working on a home assistant MQTT templated climate object which hides the MQTT control behind this single climate object. This means that in your automations you set the temperature of the climate object and the climate object will translate that in a valid P1P2 command (including HEX conversion) and send it to P1P2 over MQTT.

Please mind that not all settings are implemented yet.

The LWT (Leaving Water Temperature) is defined as follows:
```
- name: LWT Daikin
  retain: false
  qos: 0
  payload_on: 1
  payload_off: 0
  # Room temperature
  current_temperature_topic: P1P2/P/155/T/1/Temperature_Leaving_Water
  current_temperature_template: >-
    {{ value | float | round(1) }}
  # Target temperature
  temperature_state_topic: "P1P2/P/155/S/0/Target_Temperature_Heating_Zone_Main_Abs"
  temperature_state_template: >-
    {{ value | float | round(1) }}
  temperature_command_topic: "P1P2/W"
  temperature_command_template: >
    {{ 'E36 6 %04X' | format(((value | float) * 10) | int) }}
  # Temperature dial
  min_temp: 40
  max_temp: 55
  temp_step: 1
  modes:
  fan_modes:

````
It is fairly simple, does not have a mode or fan.. It is just to set the leaving temperature.

The thermostat I have in the living room is a Madoka and the following climate object correctly reads:
* Actual room temperature
* Target room temperature
* Fan mode
* Operation mode

It correctly sets:
* Target room temperature

At this moment it does not:
* Set the fan speed (silent mode)
* Set operation mode (On off, heat, etc)

The commands are redirected to a dummy MQTT topic (P1P2/W-XX) to prevent messing with the Daikin settings

```
- name: Living room Daikin
  retain: false
  qos: 0
  payload_on: 1
  payload_off: 0
  # Room temperature
  current_temperature_topic: P1P2/P/155/T/0/Temperature_Room
  current_temperature_template: >-
    {{ value | float | round(1) }}
  # Target temperature
  temperature_state_topic: "P1P2/P/155/S/0/Target_Temperature_Room"
  temperature_state_template: >-
    {{ value | float | round(1) }}
  temperature_command_topic: "P1P2/W"
  temperature_command_template: >
    {{ 'E36 0 %02X' | format(((value | float) * 10) | int) }}
  # Temperature dial
  min_temp: 19
  max_temp: 24
  temp_step: 0.5
  #########################
  ##
  ## Work in progress
  ##
  #########################
  # Mode
  mode_state_topic: P1P2/P/155/S/0/Operation_Mode_01
  mode_state_template: >-
    {% set modes = { '0':'off', '1':'heat',  '2':'cool', '3':'auto'} %}
    {{ modes[value] if value in modes.keys() else 'off' }}
  mode_command_topic: &commandTMPTopic "P1P2/W-XX"
  #mode_command_template:
  modes:
    - auto
    - heat
    - cool
    - "off"
  # Fan
  fan_mode_state_topic: P1P2/P/155/S/0/Quiet_Mode
  fan_mode_state_template: >
    {% set modes = { '0':'high', '1':'medium',  '2':'low'} %}
    {{ modes[value] if value in modes.keys() else 'off' }}
  fan_mode_command_topic: *commandTMPTopic
  #fan_mode_command_template:
  fan_modes:
    - low
    - medium
    - high

```
An example of how to set the temperature in a automation:

```
action:
  - service: climate.set_temperature
    data:
      temperature: 21
    target:
      entity_id: climate.living_room_daikin

```
Comments and improvements welcome.
I will post further changes if this is appreciated.

Trant

**Comment by trantoriana** [comment]
Working climate objects:

```
#
# Climate for LWT (Leaving water temperature)
#
- name: LWT Daikin
  retain: false
  qos: 0
  payload_on: 1
  payload_off: 0
  # Room temperature
  current_temperature_topic: P1P2/P/155/T/1/Temperature_Leaving_Water
  current_temperature_template: >-
    {{ value | float | round(1) }}
  # Target temperature
  temperature_state_topic: "P1P2/P/155/S/0/Target_Temperature_Heating_Zone_Main_Abs"
  temperature_state_template: >-
    {{ value | float | round(1) }}
  temperature_command_topic: "P1P2/W"
  temperature_command_template: >
    {{ 'E36 6 %04X' | format(((value | float) * 10) | int) }}
  # Temperature dial
  min_temp: 40
  max_temp: 55
  temp_step: 1
  mode_state_topic: "P1P2/P/155/S/0/Heating_OnOff"
  mode_state_template: >-
    {% set modes = { '0':'off', '1':'heat'} %}
    {{ modes[value] if value in modes.keys() else 'off' }}
  modes:
    #- auto
    - heat
    #- cool
    - "off"
  fan_modes:

#
# Climate for living room (Madoka)
#
- name: Living room Daikin
  retain: false
  qos: 0
  payload_on: 1
  payload_off: 0
  # Room temperature
  current_temperature_topic: P1P2/P/155/T/0/Temperature_Room
  current_temperature_template: >-
    {{ value | float | round(1) }}
  # Target temperature
  temperature_state_topic: "P1P2/P/155/S/0/Target_Temperature_Room"
  temperature_state_template: >-
    {{ value | float | round(1) }}
  temperature_command_topic: &commandTopic "P1P2/W"
  temperature_command_template: >
    {{ 'E36 0 %02X' | format(((value | float) * 10) | int) }}
  # Temperature dial
  min_temp: 19
  max_temp: 24
  temp_step: 0.5
  # Mode : Since I have no DWT or Cooling, it only is On or Off - On is therefor just heat
  mode_state_topic: "P1P2/P/155/S/0/Heating_OnOff"
  mode_state_template: >-
    {% set modes = { '0':'off', '1':'heat'} %}
    {{ modes[value] if value in modes.keys() else 'off' }}
  mode_command_topic: *commandTopic
  mode_command_template: >
    {% set modes = { 'off':'0', 'heat':'1'} %}
    {% set mode = modes[value] if value in modes.keys() else '0' %}
    {{ 'E35 31 %01X' | format(mode | int) }}
  modes:
    #- auto
    - heat
    #- cool
    - "off"
  # Fan
  fan_mode_state_topic: "P1P2/P/155/S/0/Quiet_Mode"
  fan_mode_state_template: >
    {% set modes = { '0':'high', '1':'low'} %}
    {{ modes[value] if value in modes.keys() else 'high' }}
  fan_modes:
    - high
    - low
```
